---
title: "Untitled"
author: "Jisung"
date: "2024-11-05"
output: html_document
---
```{r}
library(tidyverse)
library(magrittr)
library(data.table)
library(ggpubr)
library(caret)
library(Metrics)
library(lubridate)
library(readxl)
library(writexl)
library(ggplot2)
library(matrixsampling)
library(invgamma)
library(progress)
library(MASS)
```

#1. 데이터 불러오기
```{r}
simul_data <- read_excel("SMC_analysis.xlsx")
```


#2. 모형 적합 
##a. covariate 개수 지정 

```{r}
#생성할 각 covariate의 개수 
p_alpha<- 3 # psqi, cesd_score, stress
q_ai <- 1 #t
p_beta <-2 #age_sub, bmi
q_bi <- 1 #t

target <- c(25,26,27,28,29,30,31)

target_trans <- target

#각 covariate의 이름 부여
name_X_alpha <- c("apob","hscrp","bmi")
name_Z_a <- c("t")
name_X_beta <- c("age_sub", "hba1c")
name_Z_b<- c("t")
```

##b.계산을 위한 함수 정의 
```{r}
#1. col_num : 변수의 이름에 따라 열 번호를 추출하는 방식을 함수화 
col_num <- function(data,vari_name){
  vari_num <- which(names(data) %in% vari_name)
  return(vari_num)
}

#2. func_exp : exp(X+Z) 꼴에 대한 계산 
func_exp <- function(X, fixed, Z, random){
  return(exp(X %*% fixed + Z %*% random))
}

#3. func_nb : 음이항 분포의 pmf 
func_nb <- function(X_beta, beta, Z_b, b_i, y,k){
  
  func_beta <- func_exp(X_beta, beta ,Z_b, b_i)
  result <- 1/(y*beta(y,1/k))*(k/(1/func_beta+k))^y*(1/(1+k*func_beta))^(1/k)
  return(result)
}

#4. common_part : full_posterior에서 모든 parameter에 대한 공통된 부분  
common_part <- function(row, alpha, beta, k){
  r <- as.numeric(row[col_num(dt_apply,"r")])
  if(r==1){
    result=0
  } else {
    alpha <- matrix(alpha, nrow=p_alpha) 
    beta <- matrix(beta, nrow=p_beta)
  
    X_alpha <- matrix(row[col_num(dt_apply ,name_X_alpha)], ncol = p_alpha)
    Z_a<- matrix(row[col_num(dt_apply ,name_Z_a)], ncol = q_ai)
    X_beta <- matrix(row[col_num(dt_apply ,name_X_beta)],ncol=p_beta)
    Z_b <- matrix(row[col_num(dt_apply ,name_Z_b)],ncol=q_bi)
    y <- as.numeric(row[col_num(dt_apply ,"cycle")])
    a_i <- matrix(row[col_num(dt_apply ,ai_index)],nrow=q_ai) #trace 적용 안하려고 ncol = 1로 설정 
    b_i <-  matrix(row[col_num(dt_apply,bi_index)],nrow=q_bi) #trace 적용 안하려고 ncol = 1로 설정 
    func_alpha <- func_exp(X_alpha, alpha ,Z_a, a_i)
    
    cal_nb <- func_nb(X_beta, beta, Z_b, b_i,y,k)
    result <- log((1/(1+func_alpha))/length(target)+(1/(1/(func_alpha)+1))*cal_nb)
  }
  return(result)
}

#5. alpha-part : alpha의 full_posterior에서 필요한 계산 
alpha_part <- function(row, alpha){
  r <- as.numeric(row[col_num(dt_apply,"r")])
  if(r==0){
    result = 0 
  } else {
    alpha<- matrix(alpha,nrow=p_alpha)
    X_alpha <- matrix(row[col_num(dt_apply,name_X_alpha)], ncol = p_alpha)
    Z_a<- matrix(row[col_num(dt_apply,name_Z_a)], ncol = q_ai)
    a_i <- matrix(row[col_num(dt_apply,ai_index)],nrow=q_ai)
    
    func_alpha <- func_exp(X_alpha, alpha ,Z_a, a_i)
    
    result <- log(1/(1/func_alpha+1))
  }
  return(result)
}

#6. beta_part : beta의 full_posterior에서 필요한 계산  
beta_part <- function(row,beta,k){
  r <- as.numeric(row[col_num(dt_apply,"r")])
  if(r==0){
    result = 0
  } else {
    beta <- matrix(beta, nrow=p_beta)
    X_beta <- matrix(row[col_num(dt_apply,name_X_beta)],ncol=p_beta)
    Z_b <- matrix(row[col_num(dt_apply,name_Z_b)],ncol=q_bi)
    y <- as.numeric(row[col_num(dt_apply,"cycle")])
    b_i <-  matrix(row[col_num(dt_apply,bi_index)],nrow=q_bi)
  
    func_beta <- func_exp(X_beta, beta ,Z_b, b_i)
  
    result <- (y*log(k/(1/func_beta+k))+(1/k)*log(1/(1+k*func_beta)))
  }
  return(result)
}

#7. k_part : k의 full_posterior에서 필요한 계산 
k_part <- function(row,beta,k) {
  r <- as.numeric(row[col_num(dt_apply,"r")])
  if(r==0){
    result = 0 
  }else{
    beta <- matrix(beta, nrow=p_beta)
    X_beta <- matrix(row[col_num(dt_apply,name_X_beta)],ncol=p_beta)
    Z_b <- matrix(row[col_num(dt_apply,name_Z_b)],ncol=q_bi)
    y <- as.numeric(row[col_num(dt_apply,"cycle")])
    b_i <-  matrix(row[col_num(dt_apply,bi_index)],nrow=q_bi)
    func_beta <- func_exp(X_beta, beta, Z_b, b_i)
  
    result <- (-log(beta(y,1/k))+y*log(k/(1/func_beta+k))+(1/k)*log(1/(1+k*func_beta)))
  }
  return(result)
}

#8. dataframe에 random effect를 붙이는 코드 
ran_eff <- function(data, cov){
  delta <- mvrnorm(s_nsubj, rep(0,q_ai+q_bi), cov) %>% as.data.frame()
  s_id_uniq <- cbind(unique(s_id),delta) 
  names(s_id_uniq)[2:(1+q_ai+q_bi)] <- random_index
  data %<>%  left_join(s_id_uniq, by=c("id"="unique(s_id)"))
  return(data)
}

#9. z-transformation
z_to_rho <- function(z) {
  return((exp(2 * z) - 1) / (exp(2 * z) + 1))
}

#10. psi matrix형태로 만들기 
form_psi <- function(sigma1, sigma2, rho){
  psi<-diag(c(sigma1,sigma2))%*%matrix(c(1, rho, rho, 1),nrow=2)%*%diag(c(sigma1,sigma2))
  return(psi)
}

#11. psi_part 
psi_part <- function(data,psi){
  ran <- data[,col_num(data, c(ai_index, bi_index))] 
  cal <- apply(ran, 1,function(r){-0.5*t(r)%*%ginv(psi)%*%r})
  result <- sum(cal)
  return(result)
}

#12. random effect part 
random_part <- function(data,psi){
  ran <- data[,col_num(data, c(ai_index, bi_index))] %>% unique()
  cal <- apply(ran, 1,function(r){-0.5*t(r)%*%ginv(psi)%*%r})
  result <- cal
  return(result)
}
```

##c. MINBM모형 적합 

```{r}
n_simul <- 1

#random index 설정 
random_index <- as.character(seq(1:(q_ai+q_bi)))
ai_index <- random_index[1:q_ai] 
bi_index <- random_index[-(1:q_ai)]
```

```{r}
for(n in 1:n_simul){
  
  #id생성 
  s_id <- simul_data$id #총 데이터 1500개 생성 

  #전체 데이터의 수 
  s_nrow <- nrow(simul_data)
  s_nsubj <- n_distinct(simul_data$id)

  dt_apply <- simul_data
  
  #MCMC iteration 준비 

  #1. 전체 iteration 값 설정 
  n.iter <-50000 #iteration 수 
  m <- 1 #chain의 개수 (multiple chain : 이후 convergence 확인 위하여)
  
  #2. 추정 parameter 빈 공간 생성 
  alpha<- array(NA, dim=c(p_alpha, n.iter, m)) # alpha : p_alpha*1 차원 
  beta <- array(NA, dim=c(p_beta, n.iter, m)) # beta : p_beta*1 차원 
  k <- array(NA, dim=c(n.iter, m)) 
  
  Omega<- array(NA, dim=c(1, n.iter,m)) #correlation 회귀 계수 
  Rho <- array(NA, dim=c(n.iter,m)) #correlation part 
  Sigma_1 <- array(NA, dim=c(n.iter,m))
  Sigma_2 <- array(NA, dim=c(n.iter,m))
  
  a_i <- array(NA, dim=c(s_nsubj, n.iter,m))
  b_i <- array(NA, dim=c(s_nsubj, n.iter,m))
  
  #3. 초기값 설정 
  for(h in 1:m){
    alpha[,1,h] <- rnorm(p_alpha,0,5)
    beta[,1,h] <- rnorm(p_beta,0,5) 
    k[1,h] <-rlnorm(1,0,1) 
    
    Omega[,1,h] <- runif(1,-1,1)
    Sigma_1[1,h] <- rlnorm(1,0,1)
    Sigma_2[1,h] <- rlnorm(1,0,1)
    Rho[1,h] <- z_to_rho(Omega[,1,h])
    #rho에 대한 회귀식 : z_transform(Omega)
  }

  #4. prior 설정 
 
  #for alpha & beta prior (normal)
  mu_alpha = rep(0,p_alpha)
  mu_beta= rep(0,p_beta)
  var_alpha = diag(c(10^2),p_alpha)
  var_beta = diag(c(10^2), p_beta)
  
  #for k prior (log-normal)
  k_mu = 0
  k_var = 100
  
  ## Omega - normal
  Omega_tau = diag(c(10^2), 1)
  
  ## Sigma - log_normal
  Sigma_mu = 0
  Sigma_var = 100
  
  #5. 부가적인 요소 설정 
  dt_apply <- simul_data
  init_ncol<-ncol(dt_apply)
  
  # Count acceptance rate 
  accept_a=0
  accept_b=0
  accept_k=0
  accept_Omega=0
  accept_Sigma_1=0
  accept_Sigma_2=0
  
  #몇 번째 simulation인지 표시 
  cat("Simulation step :",n)
  
  #MCMC시작 
  pb<-progress_bar$new(total = n.iter*m)

  #iteration 
  for (h in 1:m) {
    
    dt_apply <- dt_apply[,1:init_ncol] #random effect를 제외한 df구성 
    
    #Random effect sampling
    init_psi <- form_psi(Sigma_1[1,h], Sigma_2[1,h], Rho[1,h])
    dt_apply <- ran_eff(dt_apply, init_psi)
    
    a_i[,1,h] <- unique(dt_apply[[ai_index]])
    b_i[,1,h] <- unique(dt_apply[[bi_index]])
  
    for(i in 2:n.iter){
      
      ##1.alpha
      alpha_cur <- alpha[,i-1,h]
      cal_beta <- beta[,i-1,h]
      cal_k <- k[i-1,h]
      
      #jumping distribution은 normal 
      #jumping dist의 평균은 이전 차례 sampling된 alpha의 위치를 평균으로 적용 
      alpha_prop = NULL
      for(j in 1:p_alpha){
        alpha_prop[j] <- rnorm(1, alpha_cur, diag(0.4,p_alpha)) 
        }
        
      alpha_num <- sum(apply(dt_apply,1, common_part,alpha_prop,cal_beta,cal_k)+apply(dt_apply,1,alpha_part,alpha_prop))
    
      alpha_den <- sum(apply(dt_apply,1, common_part,alpha_cur, cal_beta,cal_k)+apply(dt_apply,1,alpha_part,alpha_cur))
    
      num <- alpha_num+(-0.5*t(alpha_prop-mu_alpha)%*%solve(var_alpha)%*%(alpha_prop-mu_alpha))
      
      den <- alpha_den+(-0.5*t(alpha_cur-mu_alpha)%*%solve(var_alpha)%*%(alpha_cur-mu_alpha))

      a<-min(num-den,log(1)) #probability이기에 1차원으로 도출
      
      u <- log(runif(1)) 
    
      if(u<=a){
          alpha[,i,h] <- alpha_prop 
          accept_a <- accept_a+1 # for acceptance rate 
        } else {
          alpha[,i,h] <- alpha_cur 
        }
    
      ##2.beta
      beta_cur <- beta[,i-1,h]
      cal_alpha <- alpha[,i,h]
      cal_k <- k[i-1,h]
      
      beta_prop = NULL
      for(j in 1:p_beta){
        beta_prop[j] <- rnorm(1, beta_cur[j], diag(0.2,p_beta)) #새로운 beta에 대한 추정
        }
      
      beta_num <- sum(apply(dt_apply,1, common_part, cal_alpha, beta_prop, cal_k) + apply(dt_apply,1,beta_part, beta_prop,cal_k))
    
      beta_den <- sum(apply(dt_apply,1, common_part, cal_alpha, beta_cur, cal_k) + apply(dt_apply,1,beta_part, beta_cur,cal_k))
    
      num <- beta_num +(-0.5*t(beta_prop-mu_beta)%*%solve(var_beta)%*%(beta_prop-mu_beta))
      
      den <- beta_den +(-0.5*t(beta_cur-mu_beta)%*%solve(var_beta)%*%(beta_cur-mu_beta))
      
      a<-min(num-den,log(1))
      
      u <- log(runif(1)) 
      
      if(u<=a){
          beta[,i,h] <- beta_prop 
          accept_b <- accept_b+1 #for acceptance rate 
        }else{
          beta[,i,h] <- beta_cur
        }
      
      ##3.k
      k_cur <- k[i-1,h]
      cal_alpha <- alpha[,i,h]
      cal_beta <- beta[,i,h]
      
      #jumping distribution은 gamma  
      c <- 8
      k_prop<- max(0.05,rgamma(1,k_cur*c,c))
      
      k_num <- sum(apply(dt_apply,1, common_part, cal_alpha, cal_beta, k_prop)+apply(dt_apply, 1, k_part, cal_beta, k_prop))
    
      k_den <- sum(apply(dt_apply,1, common_part, cal_alpha, cal_beta, k_cur)+apply(dt_apply, 1, k_part, cal_beta, k_cur))
    
      num <- k_num + (-log(k_prop)-(log(k_prop)-k_mu)^2/(2*k_var))-log(dgamma(k_prop,k_cur*c,c))
      den <- k_den + (-log(k_cur)-(log(k_cur)-k_mu)^2/(2*k_var))-log(dgamma(k_cur,k_prop*c,c))
    
      a<-min(num-den,log(1)) #k는 1차원 
      u <- log(runif(1)) 
      
      if(u <=  a){
          k[i,h] <- k_prop 
          accept_k <- accept_k+1 #for acceptance rate 
        }else{
          k[i,h] <- k_cur
        }
      
      ##4.Omega
      
      cal_alpha <- alpha[,i,h]
      cal_beta <- beta[,i,h]
      cal_k <- k[i,h]
      cal_Sigma_1 <- Sigma_1[i-1,h]
      cal_Sigma_2 <- Sigma_2[i-1,h]
      
      #Omega_cur, Omega_prop 지정 
      Omega_cur <- Omega[,i-1,h]
      Rho_cur <- Rho[i-1,h]
      psi_cur <- form_psi(cal_Sigma_1, cal_Sigma_2, Rho_cur)
      
      Omega_prop <- NULL
      for(j in 1:1){
        Omega_prop[j] <- rnorm(1, Omega_cur[j],0.2) #Jumping distribution
      }
   
      Rho_prop <-  z_to_rho(Omega_prop)
      psi_prop <- form_psi(cal_Sigma_1, cal_Sigma_2, Rho_prop) 

      Omega_num <- sum(apply(dt_apply,1, common_part, cal_alpha, cal_beta, cal_k)+apply(dt_apply,1,alpha_part,cal_alpha))+psi_part(dt_apply,psi_prop)-s_nrow/2*log(1-Rho_prop^2)
      
      Omega_den <- sum(apply(dt_apply,1, common_part, cal_alpha, cal_beta, cal_k)+apply(dt_apply,1,alpha_part,cal_alpha))+psi_part(dt_apply,psi_cur)-s_nrow/2*log(1-Rho_cur^2)
        
      num <- (Omega_num)+log(2/(exp(Omega_prop)+exp(-Omega_prop)))+(-0.5*t(Omega_prop)%*%solve(Omega_tau)%*%(Omega_prop))
      den <- (Omega_den)+log(2/(exp(Omega_cur)+exp(-Omega_cur)))+(-0.5*t(Omega_cur)%*%solve(Omega_tau)%*%(Omega_cur))
      
      a<- min(num-den, log(1))
      u <- log(runif(1))
      
      if(u <=  a){
        Omega[,i,h] <- Omega_prop
        Rho[i,h] <- Rho_prop 
        accept_Omega <- accept_Omega+1 #for acceptance rate 
        
        }else{
          Omega[,i,h] <- Omega_cur
          Rho[i,h] <- Rho_cur
        }
    
      ##5.Sigma1
      
      cal_alpha <- alpha[,i,h]
      cal_beta <- beta[,i,h]
      cal_k <- k[i,h]
      cal_Rho <- Rho[i,h]
      cal_Sigma_2 <- Sigma_2[i-1,h]
      
      Sigma_1_cur <- Sigma_1[i-1,h]
      psi_cur <- form_psi(Sigma_1_cur, cal_Sigma_2,cal_Rho)
      
      c<-20
      Sigma_1_prop <- NULL
      Sigma_1_prop <- rgamma(1, Sigma_1_cur*c ,c)
      
      psi_prop <- form_psi(Sigma_1_prop, cal_Sigma_2, cal_Rho) 
      
      Sigma_1_num <- sum(apply(dt_apply,1, common_part, cal_alpha, cal_beta,cal_k)+apply(dt_apply,1,alpha_part,cal_alpha))+psi_part(dt_apply,psi_prop)+(-s_nrow)*log(Sigma_1_prop)
    
      Sigma_1_den <- sum(apply(dt_apply,1, common_part, cal_alpha, cal_beta, cal_k)+apply(dt_apply,1,alpha_part,cal_alpha))+psi_part(dt_apply,psi_cur)+(-s_nrow)*log(Sigma_1_cur)
    
      num <- (Sigma_1_num) + (-log(Sigma_1_prop)-(log(Sigma_1_prop)-Sigma_mu)^2/(2*Sigma_var))-log(dgamma(Sigma_1_prop, Sigma_1_cur*c,c))
      
      den <- (Sigma_1_den) + (-log(Sigma_1_cur)-(log(Sigma_1_cur)-Sigma_mu)^2/(2*Sigma_var))-log(dgamma(Sigma_1_cur, Sigma_1_prop*c,c))
      
      a<- min(num-den, log(1))
      
      u <- log(runif(1)) 
      
      if(u <=  a){
        Sigma_1[i,h] <- Sigma_1_prop
        accept_Sigma_1 <- accept_Sigma_1+1 #for acceptance rate 
        
        }else{
          Sigma_1[i,h] <- Sigma_1_cur
          dt_apply <- dt_apply
        }
      
      ##6.Sigma2
      
      cal_alpha <- alpha[,i,h]
      cal_beta <- beta[,i,h]
      cal_k <- k[i,h]
      cal_Rho <- Rho[i,h]
      cal_Sigma_1 <- Sigma_1[i,h]
      
      Sigma_2_cur <- Sigma_2[i-1,h]
      psi_cur <- form_psi(cal_Sigma_1, Sigma_2_cur,cal_Rho)
      
      c<-20
      Sigma_2_prop <- NULL
      Sigma_2_prop <- rgamma(1, Sigma_2_cur*c ,c)
      
      psi_prop <- form_psi(cal_Sigma_1, Sigma_2_prop, cal_Rho) 
      
      Sigma_2_num <- sum(apply(dt_apply,1, common_part, cal_alpha, cal_beta,cal_k)+ apply(dt_apply,1,beta_part, cal_beta,cal_k))+psi_part(dt_apply,psi_prop)+(-s_nrow)*log(Sigma_2_prop)
    
      Sigma_2_den <- sum(apply(dt_apply,1, common_part, cal_alpha, cal_beta, cal_k)+ apply(dt_apply,1,beta_part, cal_beta,cal_k))+psi_part(dt_apply,psi_cur)+(-s_nrow)*log(Sigma_2_cur)
  
      num <-(Sigma_2_num) + (-log(Sigma_2_prop)-(log(Sigma_2_prop)-Sigma_mu)^2/(2*Sigma_var))-log(dgamma(Sigma_2_prop, Sigma_2_cur*c,c))
      
      den <- (Sigma_2_den) + (-log(Sigma_2_cur)-(log(Sigma_2_cur)-Sigma_mu)^2/(2*Sigma_var))-log(dgamma(Sigma_2_cur, Sigma_2_prop*c,c))
    
      a<- min(num-den, log(1))
      
      u <- log(runif(1)) 
      
      if(u <=  a){
        Sigma_2[i,h] <- Sigma_2_prop
        accept_Sigma_2 <- accept_Sigma_2+1 #for acceptance rate 
        
        }else{
          Sigma_2[i,h] <- Sigma_2_cur
        }
      
      ##a_i
      cal_alpha <- alpha[,i,h]
      cal_beta <- beta[,i,h]
      cal_k <- k[i,h]
      cal_Rho <- Rho[i,h]
      cal_Sigma_1 <- Sigma_1[i,h]
      cal_Sigma_2 <- Sigma_1[i,h]
      
      cal_psi <- form_psi(cal_Sigma_1, cal_Sigma_2,cal_Rho)
      
      for(l in 1:s_nsubj){
        
        ai_cur <- a_i[l,i-1,h] #a의 l번째 index current 
        ai_prop <- rnorm(1, a_i[l,i-1,h], 0.2) #a의 l번째 index proposal
        
        dt_cur <- dt_apply[dt_apply$id == l,] #i index에 해당하는 값만 추출 
        
        dt_prop <- dt_cur
        dt_prop[[ai_index]] <- ai_prop
        
        ai_num <- sum(apply(dt_prop,1, common_part, cal_alpha, cal_beta, cal_k)+
                        apply(dt_prop,1,alpha_part, cal_alpha))
        
        ai_den <- sum(apply(dt_cur,1, common_part, cal_alpha ,cal_beta,cal_k)+
                        apply(dt_cur,1,alpha_part, cal_alpha))
        
        num <- ai_num + (-nrow(dt_prop)/2*log(det(cal_psi))) + random_part(dt_prop, cal_psi)
        den <- ai_den + (-nrow(dt_cur)/2*log(det(cal_psi))) + random_part(dt_cur, cal_psi)
        
        a<-min(num-den,log(1)) 
        u <- log(runif(1)) 
        
        if(u <=  a){
          a_i[l,i,h] <- ai_prop
        }else{
          a_i[l,i,h] <- ai_cur
        }
      }
      
      #새롭게 update된 random effect를 기존의 dataset과 결합 
      delta_id <- cbind(unique(s_id), (a_i[,i,h]))
      dt_apply$`1` <- delta_id[,2][match(dt_apply$id, delta_id[,1])]
      
      ##b_i
      cal_alpha <- alpha[,i,h]
      cal_beta <- beta[,i,h]
      cal_k <- k[i,h]
      cal_Rho <- Rho[i,h]
      cal_Sigma_1 <- Sigma_1[i,h]
      cal_Sigma_2 <- Sigma_1[i,h]
      
      cal_psi <- form_psi(cal_Sigma_1, cal_Sigma_2,cal_Rho)
      
      for(l in 1:s_nsubj){
        
        bi_cur <- b_i[l,i-1,h] #a의 l번째 index current 
        bi_prop <- rnorm(1, b_i[l,i-1,h], 0.2) #a의 l번째 index proposal
        
        dt_cur <- dt_apply[dt_apply$id == l,] #i index에 해당하는 값만 추출 
        
        dt_prop <- dt_cur
        dt_prop[[bi_index]] <- bi_prop
        
        bi_num <- sum(apply(dt_prop,1, common_part, cal_alpha, cal_beta, cal_k)+
                        apply(dt_prop,1,beta_part, cal_beta, cal_k))
        
        bi_den <- sum(apply(dt_cur,1, common_part, cal_alpha ,cal_beta,cal_k)+
                        apply(dt_cur,1,beta_part, cal_beta, cal_k))
        
        num <- bi_num + (-nrow(dt_prop)/2*log(det(cal_psi))) + random_part(dt_prop, cal_psi)
        den <- bi_den + (-nrow(dt_cur)/2*log(det(cal_psi))) + random_part(dt_cur, cal_psi)
        
        a<-min(num-den,log(1)) 
        u <- log(runif(1)) 
        
        if(u <=  a){
          b_i[l,i,h] <- bi_prop
        }else{
          b_i[l,i,h] <- bi_cur
        }
      }
      
      #새롭게 update된 random effect를 기존의 dataset과 결합 
      delta_id <- cbind(unique(s_id), (b_i[,i,h]))
      dt_apply$`2` <- delta_id[,2][match(dt_apply$id, delta_id[,1])]

      pb$tick() #진행률 업데이트 
      print(paste0("현재 iteration : ",i))
    }
  }
  
  #결과 저장 
  pm <- list(alpha = alpha, beta= beta, k=k, Omega=Omega, Rho=Rho, Sigma_1=Sigma_1, Sigma_2=Sigma_2)
  file_name <- "pm_real.RData"
  save(pm,file=file_name)
  
  #Acceptance rate 
  cat('\n')
  cat("<Overall Acceptance Rate>",'\n')
  cat("Alpha :", accept_a/n.iter, '\n')
  cat("Beta :", accept_b/n.iter, '\n')
  cat("K :", accept_k/n.iter, '\n')
  cat("Omega :", accept_Omega/n.iter, '\n')
  cat("Sigma_1 :", accept_Sigma_1/n.iter, '\n')
  cat("Sigma_2 :", accept_Sigma_2/n.iter, '\n')
  
  #Posterior mean
  cat('\n')
  cat("<Posterior mean>",'\n')
  cat("Alpha :",mean(alpha[,(n.iter/2+1):n.iter,1],na.rm=T), '\n')
  cat("Beta :",mean(beta[,(n.iter/2+1):n.iter,1],na.rm=T), '\n')
  cat("K :",mean(k[(n.iter/2+1):n.iter,1],na.rm=T), '\n')
  cat("Rho :",mean(Rho[(n.iter/2+1):n.iter,1],na.rm=T), '\n')
  cat("Sigma_1 :",mean(Sigma_1[(n.iter/2+1):n.iter,1],na.rm=T), '\n')
  cat("Sigma_2 :",mean(Sigma_2[(n.iter/2+1):n.iter,1],na.rm=T), '\n')
}
```

#3. 결과 불러오기
```{r}
load("pm_real.RData")
#real data결과를 잠시 다른 곳에 저장
real_pm <- pm
```

#4. 모수 별 PM 산출 
```{r}
#alpha
pm_alpha_1 <-mean(real_pm$alpha[1,(n.iter/2+1):n.iter,1])
pm_alpha_2 <- mean(real_pm$alpha[2,(n.iter/2+1):n.iter,1])
pm_alpha_3 <- mean(real_pm$alpha[3,(n.iter/2+1):n.iter,1])
```

```{r}
#beta
pm_beta_1 <- mean(pm$beta[1,(n.iter/2+1):n.iter,1])
pm_beta_2 <- mean(pm$beta[2,(n.iter/2+1):n.iter,1])
```

```{r}
#k 
pm_k <- mean(pm$k[(n.iter/2+1):n.iter,1])
```

```{r}
#Sigma_1
pm_sigma_1 <- mean(pm$Sigma_1[(n.iter/2+1):n.iter,1])
```

```{r}
#Sigma_2
pm_sigma_2 <- mean(pm$Sigma_2[(n.iter/2+1):n.iter,1])
```

```{r}
#Rho
pm_rho <- mean(pm$Rho[(n.iter/2+1):n.iter,1])
```

#5. Trace-plot 확인하기
```{r}
n.iter = 50000
```

```{r}
#alpha
plot(pm$alpha[1,(n.iter/2+1):n.iter,1],type="l")
plot(pm$alpha[2,(n.iter/2+1):n.iter,1],type="l")
plot(pm$alpha[3,(n.iter/2+1):n.iter,1],type="l")
```

```{r}
a <- pm$alpha[1,(n.iter/2+1):n.iter,1] %>% as.data.frame()
filter_a <- a%>%
  filter(row_number() %% 10 == 0)

plot(filter_a[,1],type="l")

```

```{r}
#beta
plot(pm$beta[1,(n.iter/2+1):n.iter,1],type="l")
plot(pm$beta[2,(n.iter/2+1):n.iter,1],type="l")
```

```{r}
#k
plot(pm$k[(n.iter/2+1):n.iter,1],type="l")
```

```{r}
#sigma_1
plot(real_pm$Sigma_1[(n.iter/2+1):n.iter,1],type="l")
```

```{r}
#sigma_2
plot(real_pm$Sigma_2[(n.iter/2+1):n.iter,1],type="l")
```

```{r}
#rho
plot(pm$Rho[(n.iter/2+1):n.iter,1],type="l")
```

```{r}
sample <- rnbinom(10000, mu=4, size=0.16)
```

##a. RMSE relative
```{r}
s_alpha_1<- real_pm$alpha[1,(n.iter/2+1):n.iter,1]
sqrt(mean((s_alpha_1 - pm_alpha_1)^2))

s_alpha_2<- real_pm$alpha[2,(n.iter/2+1):n.iter,1]
sqrt(mean((s_alpha_2 - pm_alpha_2)^2))

s_alpha_3<- real_pm$alpha[3,(n.iter/2+1):n.iter,1]
sqrt(mean((s_alpha_3 - pm_alpha_3)^2))

s_beta_1<- real_pm$beta[1,(n.iter/2+1):n.iter,1]
sqrt(mean((s_beta_1 - pm_beta_1)^2))

s_beta_2<- real_pm$beta[2,(n.iter/2+1):n.iter,1]
sqrt(mean((s_beta_2 - pm_beta_2)^2))

s_k<- real_pm$k[(n.iter/2+1):n.iter,1]
sqrt(mean((s_k - pm_k)^2))

s_sigma_1<- real_pm$Sigma_1[(n.iter/2+1):n.iter,1]
sqrt(mean((s_sigma_1 - pm_sigma_1)^2))

s_sigma_2<- real_pm$Sigma_2[(n.iter/2+1):n.iter,1]
sqrt(mean((s_sigma_2 - pm_sigma_2)^2))

s_rho<- real_pm$Rho[(n.iter/2+1):n.iter,1]
sqrt(mean((s_rho - pm_rho)^2))
```

##b. Credible interval
```{r}
quantile(s_alpha_1, probs = c(0.25, 0.975))
quantile(s_alpha_2, probs = c(0.025, 0.975))
quantile(s_alpha_3, probs = c(0.025, 0.975))
quantile(s_beta_1, probs = c(0.025, 0.975))#*
quantile(s_beta_2, probs = c(0.025, 0.975))
quantile(s_k, probs = c(0.025, 0.975)) #*
quantile(s_sigma_1, probs = c(0.025, 0.975)) #*
quantile(s_sigma_2, probs = c(0.025, 0.975)) #*
quantile(s_rho, probs = c(0.025, 0.975)) #*
```

##c. effective sample size
```{r}
library(coda)
```

```{r}
# alpha1
mcmc_object <- mcmc(s_alpha_1)

ess <- effectiveSize(mcmc_object)
print(ess)

# alpha2
mcmc_object <- mcmc(s_alpha_2)

ess <- effectiveSize(mcmc_object)
print(ess)

# alpha3
mcmc_object <- mcmc(s_alpha_3)

ess <- effectiveSize(mcmc_object)
print(ess)

# beta1
mcmc_object <- mcmc(s_beta_1)

ess <- effectiveSize(mcmc_object)
print(ess)

# beta2
mcmc_object <- mcmc(s_beta_2)

ess <- effectiveSize(mcmc_object)
print(ess)


# k
mcmc_object <- mcmc(s_k)

ess <- effectiveSize(mcmc_object)
print(ess)

# sigma_1
mcmc_object <- mcmc(s_sigma_1)

ess <- effectiveSize(mcmc_object)
print(ess)

# sigma_2
mcmc_object <- mcmc(s_sigma_2)

ess <- effectiveSize(mcmc_object)
print(ess)

# rho
mcmc_object <- mcmc(s_rho)

ess <- effectiveSize(mcmc_object)
print(ess)
```

#6.비교모형 

##a. ZINB 모형
```{r}
library(TMB)
library(glmmTMB)
```

```{r}
#데이터 불러오기 
SMC <- read_excel('SMC_analysis.xlsx')
SMC$cycle_28 <- ifelse(SMC$cycle%in%c(25,26,27,28,29,30,31), 28, SMC$cycle)

#model
zinb_mixed_model <- glmmTMB(
  cycle_28 ~  -1+age_sub+hba1c+(0+t|id),      
  ziformula = ~ -1+apob+hscrp+bmi+(0+t|id),               
  family = nbinom2,              
  data = SMC
  )

summary(zinb_mixed_model)
```

##b. Hurdle 모형
```{r}
library(pscl)
library(lme4)
```

```{r}
SMC$cycle_comb <- ifelse(SMC$cycle%in%c(25,26,27,28,29,30,31), 28, SMC$cycle)

#inflated value발생 확률에 대한 modelling
model_prob <- glmer(I(cycle_comb %in% c(25:31)) ~ -1 + apob+hscrp+bmi + (0+t|id), family = binomial(link="logit"), data = SMC)
summary(model_prob)

#inflated value를 제외한 값의 전반적인 분포에 대한 modelling 
model_count <- glmer(cycle_comb ~ -1 + age_sub + hba1c+ (0+t| id), family = negative.binomial(4.3), data = SMC[SMC$cycle_comb != 28, ])

summary(model_count)
```
